[2024-09-22T09:31:00.696+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T09:31:00.715+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.echo_task manual__2024-09-22T09:30:59.331675+00:00 [queued]>
[2024-09-22T09:31:00.724+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.echo_task manual__2024-09-22T09:30:59.331675+00:00 [queued]>
[2024-09-22T09:31:00.725+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-22T09:31:00.742+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): echo_task> on 2024-09-22 09:30:59.331675+00:00
[2024-09-22T09:31:00.769+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'echo_task', 'manual__2024-09-22T09:30:59.331675+00:00', '--job-id', '371', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpeecr9t9a']
[2024-09-22T09:31:00.768+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1135) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-22T09:31:00.773+0000] {standard_task_runner.py:105} INFO - Job 371: Subtask echo_task
[2024-09-22T09:31:00.774+0000] {standard_task_runner.py:72} INFO - Started process 1137 to run task
[2024-09-22T09:31:00.837+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.echo_task manual__2024-09-22T09:30:59.331675+00:00 [running]> on host 6e2558f7c62d
[2024-09-22T09:31:00.922+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='echo_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T09:30:59.331675+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T09:30:59.331675+00:00'
[2024-09-22T09:31:00.925+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T09:31:00.930+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-22T09:31:00.932+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo created table successfully']
[2024-09-22T09:31:00.941+0000] {subprocess.py:86} INFO - Output:
[2024-09-22T09:31:00.944+0000] {subprocess.py:93} INFO - created table successfully
[2024-09-22T09:31:00.945+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-22T09:31:00.989+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T09:31:00.991+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=echo_task, run_id=manual__2024-09-22T09:30:59.331675+00:00, execution_date=20240922T093059, start_date=20240922T093100, end_date=20240922T093100
[2024-09-22T09:31:01.048+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-22T09:31:01.063+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
