[2024-09-22T12:41:32.996+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T12:41:33.012+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.echo_task manual__2024-09-22T12:40:24.083801+00:00 [queued]>
[2024-09-22T12:41:33.019+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.echo_task manual__2024-09-22T12:40:24.083801+00:00 [queued]>
[2024-09-22T12:41:33.020+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-22T12:41:33.031+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): echo_task> on 2024-09-22 12:40:24.083801+00:00
[2024-09-22T12:41:33.035+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2728) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-22T12:41:33.036+0000] {standard_task_runner.py:72} INFO - Started process 2729 to run task
[2024-09-22T12:41:33.036+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'echo_task', 'manual__2024-09-22T12:40:24.083801+00:00', '--job-id', '808', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpydgi3xpr']
[2024-09-22T12:41:33.037+0000] {standard_task_runner.py:105} INFO - Job 808: Subtask echo_task
[2024-09-22T12:41:33.074+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.echo_task manual__2024-09-22T12:40:24.083801+00:00 [running]> on host 6e2558f7c62d
[2024-09-22T12:41:33.126+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='echo_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T12:40:24.083801+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T12:40:24.083801+00:00'
[2024-09-22T12:41:33.128+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T12:41:33.130+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-22T12:41:33.132+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Successfully']
[2024-09-22T12:41:33.137+0000] {subprocess.py:86} INFO - Output:
[2024-09-22T12:41:33.141+0000] {subprocess.py:93} INFO - Successfully
[2024-09-22T12:41:33.142+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-22T12:41:33.162+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T12:41:33.163+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=echo_task, run_id=manual__2024-09-22T12:40:24.083801+00:00, execution_date=20240922T124024, start_date=20240922T124133, end_date=20240922T124133
[2024-09-22T12:41:33.177+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-22T12:41:33.189+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-22T12:41:33.191+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
