[2024-09-22T10:00:55.158+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T10:00:55.173+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.is_api_active manual__2024-09-22T10:00:54.103172+00:00 [queued]>
[2024-09-22T10:00:55.184+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.is_api_active manual__2024-09-22T10:00:54.103172+00:00 [queued]>
[2024-09-22T10:00:55.185+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-22T10:00:55.195+0000] {taskinstance.py:2888} INFO - Executing <Task(HttpSensor): is_api_active> on 2024-09-22 10:00:54.103172+00:00
[2024-09-22T10:00:55.202+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=281) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-22T10:00:55.205+0000] {standard_task_runner.py:72} INFO - Started process 285 to run task
[2024-09-22T10:00:55.208+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'is_api_active', 'manual__2024-09-22T10:00:54.103172+00:00', '--job-id', '389', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp5a7_fo2m']
[2024-09-22T10:00:55.210+0000] {standard_task_runner.py:105} INFO - Job 389: Subtask is_api_active
[2024-09-22T10:00:55.292+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.is_api_active manual__2024-09-22T10:00:54.103172+00:00 [running]> on host 6e2558f7c62d
[2024-09-22T10:00:55.351+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='is_api_active' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T10:00:54.103172+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T10:00:54.103172+00:00'
[2024-09-22T10:00:55.353+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T10:00:55.355+0000] {baseoperator.py:405} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-09-22T10:00:55.356+0000] {http.py:137} INFO - Poking: generate_data/customers
[2024-09-22T10:00:55.374+0000] {base.py:84} INFO - Retrieving connection 'http_localhost'
[2024-09-22T10:00:55.391+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2024-09-22T10:00:55.413+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T10:00:55.415+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=is_api_active, run_id=manual__2024-09-22T10:00:54.103172+00:00, execution_date=20240922T100054, start_date=20240922T100055, end_date=20240922T100055
[2024-09-22T10:00:55.428+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-22T10:00:55.446+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-22T10:00:55.448+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
