[2024-09-22T02:48:45.524+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T02:48:45.576+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_dag.create_sum_table manual__2024-09-22T02:48:43.942901+00:00 [queued]>
[2024-09-22T02:48:45.596+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_dag.create_sum_table manual__2024-09-22T02:48:43.942901+00:00 [queued]>
[2024-09-22T02:48:45.598+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-22T02:48:45.618+0000] {taskinstance.py:2888} INFO - Executing <Task(SQLExecuteQueryOperator): create_sum_table> on 2024-09-22 02:48:43.942901+00:00
[2024-09-22T02:48:45.625+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=62) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-22T02:48:45.628+0000] {standard_task_runner.py:72} INFO - Started process 66 to run task
[2024-09-22T02:48:45.635+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_table_dag', 'create_sum_table', 'manual__2024-09-22T02:48:43.942901+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/create_table_dag.py', '--cfg-path', '/tmp/tmpolzlcx5m']
[2024-09-22T02:48:45.638+0000] {standard_task_runner.py:105} INFO - Job 263: Subtask create_sum_table
[2024-09-22T02:48:45.754+0000] {task_command.py:467} INFO - Running <TaskInstance: create_table_dag.create_sum_table manual__2024-09-22T02:48:43.942901+00:00 [running]> on host 6e2558f7c62d
[2024-09-22T02:48:45.911+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table_dag' AIRFLOW_CTX_TASK_ID='create_sum_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T02:48:43.942901+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T02:48:43.942901+00:00'
[2024-09-22T02:48:45.920+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T02:48:45.926+0000] {sql.py:266} INFO - Executing: drop table if exists SUM;

create table SUM (
    cust_id varchar PRIMARY KEY,
    count decimal,
    sum numeric(2)
);
[2024-09-22T02:48:45.978+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-22T02:48:46.006+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-22T02:48:46.023+0000] {sql.py:509} INFO - Running statement: drop table if exists SUM;

create table SUM (
    cust_id varchar PRIMARY KEY,
    count decimal,
    sum numeric(2)
);, parameters: None
[2024-09-22T02:48:46.066+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T02:48:46.067+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=create_table_dag, task_id=create_sum_table, run_id=manual__2024-09-22T02:48:43.942901+00:00, execution_date=20240922T024843, start_date=20240922T024845, end_date=20240922T024846
[2024-09-22T02:48:46.144+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-22T02:48:46.205+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-22T02:48:46.214+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
