[2024-09-21T18:20:58.067+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-21T18:20:58.174+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_dag.echo_task manual__2024-09-21T18:19:22.634523+00:00 [queued]>
[2024-09-21T18:20:58.227+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_dag.echo_task manual__2024-09-21T18:19:22.634523+00:00 [queued]>
[2024-09-21T18:20:58.230+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2024-09-21T18:20:58.294+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): echo_task> on 2024-09-21 18:19:22.634523+00:00
[2024-09-21T18:20:58.333+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=160) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-21T18:20:58.339+0000] {standard_task_runner.py:72} INFO - Started process 173 to run task
[2024-09-21T18:20:58.351+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_table_dag', 'echo_task', 'manual__2024-09-21T18:19:22.634523+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/create_table_dag.py', '--cfg-path', '/tmp/tmp09pdenup']
[2024-09-21T18:20:58.381+0000] {standard_task_runner.py:105} INFO - Job 183: Subtask echo_task
[2024-09-21T18:20:58.640+0000] {task_command.py:467} INFO - Running <TaskInstance: create_table_dag.echo_task manual__2024-09-21T18:19:22.634523+00:00 [running]> on host 6e2558f7c62d
[2024-09-21T18:20:58.927+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table_dag' AIRFLOW_CTX_TASK_ID='echo_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-21T18:19:22.634523+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-21T18:19:22.634523+00:00'
[2024-09-21T18:20:58.933+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-21T18:20:58.951+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-21T18:20:58.965+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo created table successfully']
[2024-09-21T18:20:58.987+0000] {subprocess.py:86} INFO - Output:
[2024-09-21T18:20:58.988+0000] {subprocess.py:93} INFO - created table successfully
[2024-09-21T18:20:58.990+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-21T18:20:59.180+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-21T18:20:59.184+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=create_table_dag, task_id=echo_task, run_id=manual__2024-09-21T18:19:22.634523+00:00, execution_date=20240921T181922, start_date=20240921T182058, end_date=20240921T182059
[2024-09-21T18:20:59.223+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-21T18:20:59.318+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-21T18:20:59.327+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
